using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;

namespace DialogueTopicIndicator {
    public class Config {
        public bool UsePostfix = false;
        public Dictionary<string, string> RenameMap = new Dictionary<string, string>() {
            { "Skyrim.esm", "" },
            { "Update.esm", "" },
            { "Dawnguard.esm", "" },
            { "Hearthfires.esm", "" },
            { "Dragonborn.esm", "" },
            { "LegacyoftheDragonborn.esm", "LotD" },
            { "Alternate Start - Live Another Life.esp", "Alt Life" },
            { "nwsFollowerFramework.esp", "" },
        };
    }

    public class Program {
        protected static Lazy<Config> Config = null!;

        public static async Task<int> Main(string[] args) {
            Console.WriteLine(args);
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch, new PatcherPreferences() {
                })
                .SetAutogeneratedSettings("settings", "settings.json", out Config)
                .SetTypicalOpen(GameRelease.SkyrimSE, "DialogTags.esp")
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state) {
            foreach (var key in Config.Value.RenameMap.Keys.ToList()) {
                Config.Value.RenameMap[key.ToLower()] = Config.Value.RenameMap[key];
            }

            var records = state.LoadOrder.ListedOrder.DialogTopic().WinningOverrides();
            foreach (var dialogTopic in records) {
                var name = dialogTopic.FormKey.ModKey.ToString();
                var key = name.ToLower();
                if (Config.Value.RenameMap.ContainsKey(key)) {
                    name = Config.Value.RenameMap[key];
                    if (name == "") {
                        continue;
                    }
                } else {
                    if (name.EndsWith(".esm") || name.EndsWith(".esp") || name.EndsWith(".esl")) {
                        name = name.Remove(name.Length - 4);
                    }

                    Config.Value.RenameMap[key] = name;
                }

                if (dialogTopic.Name != null && dialogTopic.Name.String != null && dialogTopic.Name.String != "") {
                    var patchedRecord = state.PatchMod.DialogTopics.GetOrAddAsOverride(dialogTopic);
                    if (Config.Value.UsePostfix) {
                        patchedRecord.Name += $" [{name}]";
                    } else {
                        patchedRecord.Name = $"[{name}] " + patchedRecord.Name;
                    }
                }
            }

            state.PatchMod.ModHeader.Flags |= SkyrimModHeader.HeaderFlag.Light;
        }
    }
}